CREATE DEFINER=`root`@`localhost` PROCEDURE `MY_SELECT`(OUT RES VARCHAR(1000))
BEGIN
    DECLARE RES VARCHAR(1000) DEFAULT "";
    DECLARE RES_NAME VARCHAR(20);
    DECLARE RES_EMPNO INT;
    DECLARE done INT DEFAULT FALSE; 
    DECLARE cur1 CURSOR FOR SELECT ENAME, EMPNO FROM MY_EMP.MY_EMP;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;
    
    open cur1;
    read_loop: LOOP
       FETCH cur1 INTO RES_NAME, RES_EMPNO;
       IF done THEN
          LEAVE read_loop;
	   END IF;
	   SET RES = CONCAT(RES_NAME,", ", RES_EMPNO);
	END LOOP;
    
    close cur1;
END